name: node ci setup
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env: 
      CI : true
    strategy: 
      matrix: 
        node-version: [14.x,16.x]
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: node setup with version 16
       uses: actions/setup-node@v3
       with:
        node-version: "16"
<<<<<<< HEAD
    #  - run: npm run client-install
=======
        
     - name: Install modules
       run: npm run client-install
>>>>>>> 65511b62d801111325ebc200ff64c7b22efccc58


