name: node ci setup
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env: 
      CI : true
    strategy: 
      matrix: 
        node-version: [14.x,16.x]
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: node setup with version  ${{matrix.node-version}}
       uses: actions/setup-node@v3
       with:
        node-version: ${{matrix.node-version}}
     - run: npm run server-install
     - run: npm run test


