name: node ci setup
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: node setup with version 16
       uses: actions/setup-node@v3
       with:
        node-version: "16"
        
     - name: Install modules
       run: npm run client-install


