name: node ci setup
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: node setup with version 16
       uses: actions/setup-node@v2
       with:
        node-version: "16"
<<<<<<< HEAD
     - run: npm run client-install
=======
     - run: npm run build
>>>>>>> a6649b27336d352fde385e8d52eb6ac8f4fd5f28


